print(' O tipo primitivo desse valor é ', type(a))
print('Só tem espaças? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É afabético? ', a.isalpha())
print('Está em maiúsculas? ', a.isupper())
print('Está em minúsculas? ', a.islower())
print('Está capitalizada? ', a.istitle())
